### ISSUE TITLE
Bad merge on border-width-x merge

### ISSUE THREAD

**Issue by mikaelec** [ben-eb/postcss-merge-longhand#20]
I have a class style with (lots of !important, I know...):
```
    [... other border-x-x styling]
    border-top-width: 1px !important;
    border-right-width: 1px !important;
    border-bottom-left-radius: 1px !important;
    border-bottom-width: 1px !important;
    [... other border-x-x styling]
```

Which merges to:
```
    border: 1px !important;
```

Which effectively removes my other border styles, previously set.
Should the merge not be to `border-width: 1px !important`?

**Comment by ben-eb** [comment]
Can you post the full rule that is causing this problem? With your sample code everything is working correctly:

```css
h1{border-top-width:1px!important;border-right-width:1px!important;border-bottom-left-radius:1px!important;border-bottom-width:1px!important}
```
