### ISSUE TITLE
Support overriding shorthand properties

### ISSUE THREAD

**Issue by btpoe** [ben-eb/postcss-merge-longhand#22]
It would be great to be able to write:

``` css
a {
  padding: 3px;
  padding-left: 5px;
}
```

and have it condense to:

``` css
a {
  padding: 3px 3px 3px 5px;
}
```

Currently, the lib only supports merging if all longhand properties are declared.
