### ISSUE TITLE
Broken if duplicate property exists

### ISSUE THREAD

**Issue by XiaoxiaoPu** [ben-eb/postcss-merge-longhand#25]
Before:
```css
a {
    padding-bottom: 0.5em;
    padding-left: 0.625em;
    padding-right: 0.625em;
    padding-top: 0.5em;
    padding-right: 2.5em;
}
```

After:
```css
a{padding:.5em 2.5em .5em .625em;padding-right:.625em}
```

Expected:
```css
a{padding:.5em 2.5em .5em .625em}
```
