### ISSUE TITLE
CSS Custom Variables should not be processed

### ISSUE THREAD

**Issue by iahu** [ben-eb/postcss-merge-longhand#27]
input
```css
h1{--margin-top:10px;--margin-right:10px;--margin-bottom:10px;--margin-left:10px;}
h1{--my-margin-top:10px;--my-margin-right:20px;--my-margin-bottom:30px;--my-margin-left:40px}
```

output:
```css
h1{margin:10px}
h1{margin:10px 20px 30px 40px}
```

expect `as some as the input`
