### ISSUE TITLE
Border merge crash with none

### ISSUE THREAD

**Issue by pdanpdan** [ben-eb/postcss-merge-longhand#28]
Hello.

```css
.test {
  border: 1px none red;
  border-bottom-style: solid;
}
```

Crashes with unknown property toLowerCase of undefined.
